"""Drop legacy working_commits table

The working_commits table was used in the legacy facade system to track
partially-processed commits so collection could resume if interrupted.
With the new ORM-based system, commits are written directly to the commits
table, making this table obsolete.

Revision ID: 38
Revises: 37
Create Date: 2025-01-10 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38'
down_revision = '37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('working_commits', schema='augur_data')
    op.drop_table('working_commits', schema='augur_operations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('working_commits',
    sa.Column('repos_id', sa.Integer(), nullable=False),
    sa.Column('working_commit', sa.String(40), server_default="'NULL'::character varying", nullable=True),
    schema='augur_operations',
    comment='For future use when we move all working tables to the augur_operations schema. '
    )
    
    op.create_table('working_commits',
    sa.Column('repos_id', sa.Integer(), nullable=False),
    sa.Column('working_commit', sa.String(40), server_default="'NULL'::character varying", nullable=True),
    schema='augur_data'
    )
    # ### end Alembic commands ###
